services:
  bdd-test:
    build:
      context: ./bdd-test
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      idemax:
        condition: service_healthy
    command: ["/bin/sh", "-c", "exec /app/execute_tests.sh"]
