services:
  bdd-test:
    build:
      context: ./bdd-test
      dockerfile: Dockerfile
    volumes:
      - ./reports:/app/output
    depends_on:
      - idemax
      - redis
      - zookeeper
      - kafka
