version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  idempotency-service:
    build:
      context: ./idemax  # Ensure Dockerfile location is correct
      dockerfile: Dockerfile
    container_name: idempotency-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis:6379

volumes:
  redis_data:
    driver: local
