
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  idemax:
    build:
      context: ./idemax
      dockerfile: Dockerfile
    container_name: idemax
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis:6379

volumes:
  redis_data:
    driver: local
